### ISSUE TITLE
Error on vagrant up command

### ISSUE THREAD

**Issue by Bshally** [Nav33d/craftcms-installer#1]
I get this error when entering the vagrant up command:

```
Bringing machine 'crafty' up with 'virtualbox' provider...
==> crafty: [vagrant-faster] Setting CPUs: 2, Memory: 4096
==> crafty: Importing base box 'laravel/homestead'...
==> crafty: Matching MAC address for NAT networking...
==> crafty: Checking if box 'laravel/homestead' is up to date...
==> crafty: Setting the name of the VM: crafty
==> crafty: Clearing any previously set network interfaces...
==> crafty: Preparing network interfaces based on configuration...
    crafty: Adapter 1: nat
    crafty: Adapter 2: hostonly
==> crafty: Forwarding ports...
    crafty: 80 (guest) => 8000 (host) (adapter 1)
    crafty: 443 (guest) => 44300 (host) (adapter 1)
    crafty: 3306 (guest) => 33060 (host) (adapter 1)
    crafty: 5432 (guest) => 54320 (host) (adapter 1)
    crafty: 22 (guest) => 2222 (host) (adapter 1)
==> crafty: [vagrant-faster] Setting CPUs: 2, Memory: 4096
==> crafty: Running 'pre-boot' VM customizations...
==> crafty: Booting VM...
==> crafty: Waiting for machine to boot. This may take a few minutes...
    crafty: SSH address: 127.0.0.1:2222
    crafty: SSH username: vagrant
    crafty: SSH auth method: private key
    crafty: Warning: Remote connection disconnect. Retrying...
    crafty: 
    crafty: Vagrant insecure key detected. Vagrant will automatically replace
    crafty: this with a newly generated keypair for better security.
    crafty: 
    crafty: Inserting generated public key within guest...
    crafty: Removing insecure key from the guest if it's present...
    crafty: Key inserted! Disconnecting and reconnecting using new SSH key...
==> crafty: Machine booted and ready!
==> crafty: Checking for guest additions in VM...
==> crafty: Setting hostname...
==> crafty: Configuring and enabling network interfaces...
==> crafty: Mounting shared folders...
    crafty: /vagrant => /Users/bshallenberger/Desktop/Project-HQ/crafty
    crafty: /home/vagrant/crafty => /Users/bshallenberger/Desktop/Project-HQ/crafty
==> crafty: Running provisioner: shell...
    crafty: Running: inline script
==> crafty: 
==> crafty: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC1zNw2JRgve7FzpiEbyqKo5UrScgqe5u7ci5fOLbHIXEeZ8GGED0Q52zQAO9MKVb8mddqqJTD0gGXvDPdPlEWVKIhn14yJhakW54ep2oIgc0BiqBEzMEkg6qvYifzLrBwdfBrVpvCjKOI16w5hNZ6IZKI2ozAWfq2exSvD1XBkbkq0aQlip/m96Te1S3KJnxvyvpW/aw29nLrVrKUTEeKTpzTu7YtVLNKskj4/PaMcVwe2a2PpHYB2aFdMlQVloBQwIpN30zHA+ITGnYQJ1e51dMQhs0N6h+q0mSZo59MRwQJOSHb8wJ2HXCixkwqFbhXFPb5cjKuuex+5MJl5PYNjsA55bMGZwGV0OhujCzQZHnxk9evYrRvh8lT2yChgvZ2KRZ7UPzD8yUjFX4LOwXDU6p4xo+tmhqKpcOfB9ifDzfTnhKb4PCz+4RAgpyUYH2GBRwwSh1udMmzYXjrB8x0Kv8JDWcMAydG+p98tELFEHE+WiE8M2jlHrhAFl/4k6ZQSQxZGPpoRF2kqpZOhuL8MZE75fS3MVDzqWUOL0s59yaJ3oWm8FLtz+boANLp9kpUwhdFN0aPM7w1fTlNAm7H0jF/JVTOXuqjdSwxP21FI/x3NW3fIBdHgR8cm0RjXGW5KUSo3Bu464/7J82F+ul8evlSCmyowOCUtW9tA8szOqw== folder@seorigami.com
==> crafty: Running provisioner: shell...
    crafty: Running: inline script
==> crafty: Running provisioner: shell...
    crafty: Running: /var/folders/b4/d7n1ph0178z8lc1yfnq299yr0000gn/T/vagrant-shell20161229-3669-ijqx0b.sh
==> crafty: Running provisioner: shell...
    crafty: Running: script: Creating Site: crafty.dev
==> crafty: Running provisioner: shell...
    crafty: Running: script: Restarting Nginx
==> crafty: Failed to restart php7.0-fpm.service: Unit php7.0-fpm.service not found.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by Nav33d** [comment]
@Bshally Can you please run this command and let me know the version(s) of Homestead box installed on your machine: `vagrant box list` and could you please confirm version of installer you running `composer global show`

Many thanks

**Comment by Bshally** [comment]
I've been trying to follow some suggestions from people having similar issues, as such I've done some updates since posting this issue.  `vagrant box list` brings back :
```
laravel/homestead (virtualbox, 1.0.1)
scotch/box        (virtualbox, 2.5)
```
Scotch box is a box I use for Wordpress development. It is currently off.

And `composer global show` brings back: 
```
guzzlehttp/guzzle         6.2.2  Guzzle is a PHP HTTP client library
guzzlehttp/promises       v1.3.1 Guzzle promises library
guzzlehttp/psr7           1.3.1  PSR-7 message implementation
nav33d/craftcms-installer v0.1.7 Craft CMS local develoment installer.
psr/http-message          1.0.1  Common interface for HTTP messages
psr/log                   1.0.2  Common interface for logging libraries
symfony/console           v3.2.1 Symfony Console Component
symfony/debug             v3.2.1 Symfony Debug Component
symfony/polyfill-mbstring v1.3.0 Symfony polyfill for the Mbstring extension
symfony/process           v3.2.1 Symfony Process Component
```

I've been trying to do some fixes from https://www.joeferguson.me/laravel-homestead-4-0-and-box-1-0/ which broke the after.sh so I had to do the change manually like in the video tutorial. At this point I've gotten the `vagrant up` to go ahead without errors. Now I'm stuck with the following when I try to go to crafty.dev/admin to install craft: 
![screen shot 2016-12-30 at 11 05 53 am](https://cloud.githubusercontent.com/assets/3440317/21568137/02c0711c-ce80-11e6-9e1c-ef9ccb5e0419.png)

After this I've tried installing mcrypt as shown here: https://medium.com/@didgeoridoo/how-to-get-craft-cms-2-5-running-on-a-laravel-homestead-3-0-x-vagrant-box-556fe57ff807#.6xhz0wkp9 using 
```
vagrant ssh
sudo apt-get update
sudo apt-get install php7.0-mcrypt
```
This still brings me back to the mcrypt screen above. I've been trying to get Craft up on homestead for 2 days now. I've followed many different tutorials, started from scratch again after removing composer and homestead, and just about anything else. Any help is appreciated.

**Comment by Nav33d** [comment]
@Bshally It is an easy fix, are you on Craft Slack channel? I will write instructions here for you:

- Remove vagrant box. Run this command `vagrant box remove laravel/homestead`. 
- Confirm that box has successfully been removed by running `vagrant box list`
- Add laravel homestead box version 0.5.0 by running this command `vagrant box add laravel/homestead --box-version 0.5.0`
- Now you can use craft cms installer to run the setup and it should work just fine.

Let me know if that works if not I'm online most of the time on Craft CMS Slack channel https://craftcms.com/community#slack.

Many thanks

**Comment by Bshally** [comment]
THANK YOU! This fixed it. I still had to do the `/etc/mysql/my.cnf ` edit manually for some reason, but it finally got me to the installation process. The error from vagrant up I get from that is:  `/tmp/vagrant-shell: line 4: /etc/mysql/my.cnf: Permission denied` . 

In any case, thank you so much! I've also joined the slack channel as well.

**Comment by Nav33d** [comment]
@Bshally Glad you got it working. I expected that issue. Next time before running vagrant up if you open up `vagrantfile` and find this block

``` 
if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: true
    end
```

and set the privileged to `true` it will fix that issue as well.

I will fix this in the next release of the installer.
